- hosts: kubemaster
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: "Add K8S Token dummy host"
      add_host:
        name:   "K8S_TOKEN_HOLDER"
        join_command:  "{{ join_command_raw.stdout_lines[0] }}"

#    - name: set join command
#      set_fact:
#        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: kubenode
  become: yes
  tasks:
#    - debug:
#        msg: "{{hostvars}}"

    - name: join cluster
      shell: "{{ hostvars['K8S_TOKEN_HOLDER'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt